# Comprehensive Guide to NumPy Functions

NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently.





## Installation

If you haven't installed NumPy yet, you can do so using `pip`:

```python


In [43]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: C:\Users\user\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip


# Importing NumPy
It's a common convention to import NumPy using the alias np:

In [2]:
import numpy as np

# Array Creation
## From Lists
You can create NumPy arrays from Python lists or tuples using the np.array() function.



In [4]:
import numpy as np

# Creating a 1D array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Creating a 2D array from a list of lists
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)


1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]


# Zeros and Ones
Creating arrays filled with zeros or ones is straightforward with np.zeros() and np.ones().

In [6]:
# Array of zeros
zeros = np.zeros((3, 4))
print("Zeros Array:\n", zeros)

# Array of ones
ones = np.ones((2, 3))
print("\nOnes Array:\n", ones)


Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


# Arange and Linspace
Generate sequences of numbers using np.arange() and np.linspace().

In [8]:
# Using arange to create an array of even numbers
evens = np.arange(0, 10, 2)
print("Even Numbers:", evens)

# Using linspace to create an array of 5 numbers between 0 and 1
linear = np.linspace(0, 1, 5)
print("\nLinspace Array:", linear)


Even Numbers: [0 2 4 6 8]

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


# Random Arrays
Generate arrays with random numbers using np.random.

In [10]:
# Random integers between 0 and 10
rand_int = np.random.randint(0, 10, size=(2, 3))
print("Random Integers:\n", rand_int)

# Random floats between 0 and 1
rand_float = np.random.random((3, 2))
print("\nRandom Floats:\n", rand_float)


Random Integers:
 [[7 9 9]
 [4 7 6]]

Random Floats:
 [[0.99933405 0.12260725]
 [0.53632669 0.17735993]
 [0.18156206 0.97804041]]


# Array Attributes
NumPy arrays have several useful attributes.

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)
print("Size:", arr.size)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Data Type: int32
Size: 6


# Indexing and Slicing
## Basic Indexing
Accessing elements using indices.

In [14]:
arr = np.array([10, 20, 30, 40, 50])

# Access the first element
print("First Element:", arr[0])

# Access the last element
print("Last Element:", arr[-1])


First Element: 10
Last Element: 50


# Slicing
Extracting subarrays using slicing.

In [16]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Slice the first two rows and first three columns
sub_arr = arr[0:2, 0:3]
print("Sliced Array:\n", sub_arr)


Sliced Array:
 [[1 2 3]
 [5 6 7]]


# Boolean Indexing
Selecting elements based on conditions.

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Select elements greater than 3
filtered = arr[arr > 3]
print("Elements > 3:", filtered)


Elements > 3: [4 5 6]


# Fancy Indexing
Using integer arrays to specify multiple indices.

In [20]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

# Select elements at specific positions
selected = arr[[0, 1, 2], [0, 1, 0]]
print("Fancy Indexed Elements:", selected)


Fancy Indexed Elements: [1 4 5]


# Array Operations
## Arithmetic Operations
Perform element-wise operations.

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
print("Addition:", a + b)

# Subtraction
print("Subtraction:", a - b)

# Multiplication
print("Multiplication:", a * b)

# Division
print("Division:", a / b)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


# Universal Functions (ufuncs)
Apply mathematical functions element-wise.

In [25]:
arr = np.array([1, 4, 9, 16])

# Square root 
sqrt = np.sqrt(arr)
print("Square Roots:", sqrt)

# Exponential
exp = np.exp(arr)
print("\nExponential:", exp)

# Sine
angles = np.array([0, np.pi/2, np.pi])
sine = np.sin(angles)
print("\nSine Values:", sine)


Square Roots: [1. 2. 3. 4.]

Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]

Sine Values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


# Linear Algebra
Perform linear algebra operations using numpy.linalg.

In [28]:
import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
product = np.dot(A, B)
print("Matrix Product:\n", product)

# Transpose
transpose = A.T
print("\nTranspose of A:\n", transpose)

# Inverse
inverse_A = np.linalg.inv(A)
print("\nInverse of A:\n", inverse_A)

# Determinant
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)


Matrix Product:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of A: -2.0000000000000004


# Statistics
Compute statistical measures.

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Mean
mean = np.mean(arr)
print("Mean:", mean)

# Median
median = np.median(arr)
print("Median:", median)

# Standard Deviation
std = np.std(arr)
print("Standard Deviation:", std)

# Sum
total = np.sum(arr)
print("Sum:", total)

# Minimum and Maximum
minimum = np.min(arr)
maximum = np.max(arr)
print("Min:", minimum, "Max:", maximum)


Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Sum: 21
Min: 1 Max: 6


# Saving and Loading Arrays
Save arrays to disk and load them back.

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Save to a binary file in NumPy `.npy` format
np.save('array.npy', arr)

# Load the array back
loaded_arr = np.load('array.npy')
print("Loaded Array:\n", loaded_arr)

# Save multiple arrays in a single file using `.npz` format
np.savez('arrays.npz', a=arr, b=loaded_arr)

# Load the `.npz` file
data = np.load('arrays.npz')
print("\nLoaded Arrays from .npz:")
print("a:\n", data['a'])
print("b:\n", data['b'])


Loaded Array:
 [[1 2 3]
 [4 5 6]]

Loaded Arrays from .npz:
a:
 [[1 2 3]
 [4 5 6]]
b:
 [[1 2 3]
 [4 5 6]]


# Advanced Topics


## Broadcasting
Perform operations on arrays of different shapes.

In [37]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

# Add a 1D array to a 2D array
result = a + b
print("Broadcasted Addition:\n", result)


Broadcasted Addition:
 [[11 22 33]
 [14 25 36]]


# Reshaping Arrays
Change the shape of an array without changing its data.

In [38]:
arr = np.arange(12)
print("Original Array:", arr)

# Reshape to 3x4
reshaped = arr.reshape((3, 4))
print("\nReshaped Array (3x4):\n", reshaped)

# Flatten the array back to 1D
flat = reshaped.flatten()
print("\nFlattened Array:", flat)


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


# Stacking and Splitting
Combine or divide arrays.

In [40]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Vertical Stacking
v_stack = np.vstack((a, b))
print("Vertical Stack:\n", v_stack)

# Horizontal Stacking
h_stack = np.hstack((a, b.T))
print("\nHorizontal Stack:\n", h_stack)

# Splitting
split = np.split(v_stack, [2], axis=0)
print("\nSplit Arrays:")
for part in split:
    print(part)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]]

Horizontal Stack:
 [[1 2 5]
 [3 4 6]]

Split Arrays:
[[1 2]
 [3 4]]
[[5 6]]


# Copy vs. View
Understanding the difference between copying and viewing arrays.

In [42]:
arr = np.array([1, 2, 3, 4])

# View
view = arr.view()
view[0] = 100
print("Original Array after View Modification:", arr)

# Copy
copy = arr.copy()
copy[1] = 200
print("Original Array after Copy Modification:", arr)
print("Copied Array:", copy)


Original Array after View Modification: [100   2   3   4]
Original Array after Copy Modification: [100   2   3   4]
Copied Array: [100 200   3   4]


<center>
    <p style="
        font-family: 'Verdana', sans-serif;
        font-size: 20px;
        color: #333333;
        font-weight: bold;
        line-height: 1.6;
        text-align: center;
        margin: 30px 0;
    ">
        <span style="color: #1E90FF; font-size: 22px;">🚀 Connect with me on LinkedIn!</span><br>
        <span style="font-size: 18px; color: #4CAF50;">
            For more insights and updates on Python programming and advanced concepts, feel free to
        </span><br>
        <span style="font-size: 18px;">
            <strong><a href="https://www.linkedin.com/in/swadhin-gyanajyoti-nayak/" style="color: #FF4500; text-decoration: none; font-weight: bold;">connect with Swadhin Gyanajyoti Nayak</a></strong>.
        </span>
    </p>
</center>
